# Generated by Django 6.0.6 on 2026-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='group',
            name='title_normalized',
            field=models.CharField(db_index=True, default='exite', editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.BigIntegerField(editable=False, unique=True),
        ),
    ]
