# Generated by Django 6.0.6 on 2026-06-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_group_options_group_title_normalized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title_normalized',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
