# Generated by Django 6.0.6 on 2026-07-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_backup_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup_code',
            name='hash_code',
            field=models.CharField(max_length=255),
        ),
    ]
