# Generated by Django 6.0.6 on 2026-07-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_alter_backup_code_hash_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
