# Generated by Django 6.0.6 on 2026-07-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_alter_domain_domain_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='group_id',
        ),
        migrations.AddField(
            model_name='domain',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='domains', to='identity.group'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
