# Generated by Django 6.0.6 on 2026-06-27 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_domain_tag_user_domain_tag'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user_domain_tag',
            name='unique_user_tag_per_domain',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='title_normalized',
            new_name='tag_title_normalized',
        ),
        migrations.RenameField(
            model_name='user_domain_tag',
            old_name='domain_id',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='user_domain_tag',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='user_domain_tag',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_title',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domain',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_domains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_name',
            field=models.TextField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='user_domain_tag',
            constraint=models.UniqueConstraint(fields=('user', 'domain'), name='unique_user_tag_per_domain'),
        ),
    ]
