# Generated by Django 6.0.6 on 2026-07-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_remove_domain_group_id_domain_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
