# Generated by Django 6.0.6 on 2026-06-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_domain_tag_unique_user_tag_per_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='group_id',
            field=models.ManyToManyField(to='accounts.group'),
        ),
    ]
