# Generated by Django 6.0.6 on 2026-07-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_alter_tag_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_title_normalized',
            new_name='title_normalized',
        ),
    ]
