# Generated by Django 6.0.6 on 2026-07-27 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_rename_tag_title_tag_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('limited', 'Limited'), ('regular', 'Regular'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Username must be at least 5 characters long.'), django.core.validators.RegexValidator(code='invalid_username_characters', message='Username can only contain letters, numbers, underscores, and hyphens.', regex='^[A-Za-z0-9_-]+$'), django.core.validators.RegexValidator(code='numeric_username_not_allowed', message='Username cannot consist of numbers only.', regex='^(?!\\d+$)')]),
        ),
    ]
