# Generated by Django 6.0.6 on 2026-08-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_tag_deleted_at_tag_updated_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user_domain_tag',
            name='unique_user_tag_per_domain',
        ),
        migrations.AddConstraint(
            model_name='user_domain_tag',
            constraint=models.UniqueConstraint(fields=('user', 'domain', 'tag'), name='unique_user_tag_per_domain'),
        ),
    ]
