# Generated by Django 6.0.6 on 2026-08-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_remove_user_domain_tag_unique_user_tag_per_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_domain_tag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
