# Generated by Django 6.0.6 on 2026-08-07 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_user_domain_tag_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر نیست. باید با 09 شروع شده و 11 رقم باشد.', regex='^09\\d{9}$')]),
        ),
    ]
