# Generated by Django 6.0.6 on 2026-08-08 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0012_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر نیست. باید با 09 شروع شده و 11 رقم باشد.', regex='^09\\d{9}$')]),
        ),
    ]
