# Generated by Django 6.0.6 on 2026-08-13 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='groups',
        ),
        migrations.AddField(
            model_name='domain',
            name='groups',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='identity.group'),
            preserve_default=False,
        ),
    ]
