# Generated by Django 6.0.6 on 2026-08-16 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_remove_domain_groups_domain_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='identity.group'),
        ),
    ]
