# Generated by Django 6.0.6 on 2026-08-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_alter_domain_groups'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user_domain_tag',
            name='unique_user_tag_per_domain',
        ),
        migrations.AddConstraint(
            model_name='user_domain_tag',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'domain', 'tag'), name='unique_user_tag_per_domain'),
        ),
    ]
