# Generated by Django 6.0.6 on 2026-08-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0016_remove_user_domain_tag_unique_user_tag_per_domain_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usergroup',
            name='unique_primary_group_per_user',
        ),
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'group'), name='unique_active_user_group'),
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_primary', True)), fields=('user',), name='unique_primary_group_per_user'),
        ),
        migrations.AlterModelTable(
            name='usergroup',
            table=None,
        ),
    ]
