# Generated by Django 6.0.6 on 2026-08-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0017_remove_usergroup_unique_primary_group_per_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='groups',
            new_name='group',
        ),
    ]
